name: Build and Deploy to GitHub Pages

on:
  schedule:
    - cron: '0 8 * * *'  # Runs at 3 AM EST (8 AM UTC)
  workflow_dispatch:

# defaults: run: shell: bash

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: python-ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  setup:
    name: Python Setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/python_deps

  build:
    name: Build and Publish Static Site 
    runs-on: ubuntu-latest
    needs: setup

    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/python_deps

      - name: Generate Static Site
        run: poetry run save_static_site --output-dir static_site

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'static_site'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4